version: "3.8"
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: the_database
    restart: always
    platform: linux/amd64
    ports:
      - "8890:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: the_database
    volumes:
      - data:/var/lib/mysql
volumes:
  data:
